# DATASET VARIAABLES
INPUT_CHUNK_LEN = 120 # 2 MINUTES
OUTPUT_CHUNK_LEN = 10 # 10 SECONDS
WINDOW_STRIDE = 1
GAP = 0

# DARTS TFT MODEL VARIABLES
BATCH_SIZE = 128
HIDDEN_SIZE = 32 
LSTM_LAYERS = 2
ATT_HEADS = 4
DROPOUT = 0.1

# OTHER MODEL VARIABLES
N_LAYERS = 3
D_MODEL = 128
N_HEADS = 16

# TRAINING VARIABLES
L_RATE = 1e-5
EPOCH = 5
RANDOM_SEED = 42
SAMPLE_PER_TS = 1000 # change later after calculating based on input and output optimal chunk

# TEST VARIABLES
PRED_ITERATE = 50