INPUT_CHUNK_LEN = 120 # 2 MINUTES
OUTPUT_CHUNK_LEN = 30 # 30 SECONDS

# MODEL VARIABLES
BATCH_SIZE = 64
HIDDEN_SIZE = 32 
LSTM_LAYERS = 2
ATT_HEADS = 4
DROPOUT = 0.1

# TRAINING VARIABLES
L_RATE = 1e-3
EPOCH = 5
RANDOM_SEED = 42
SAMPLE_PER_TS = 100 # get 1000 random windows for training
